builds:
  - main: main.go
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

changelog:
  sort: desc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch

archives:
  - id: default
    format: zip
    name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}"
