git:
  short_hash: true

builds:
  - main: main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ldflags: "-s -w -X main.Version={{.Version}}"


changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch

archive:
  format_overrides:
    - goos: windows
      format: zip
  name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}"
  replacements:
    amd64: amd64
    darwin: mac
    linux: linux
    windows: windows